QubesOS/qubes-manager

qubesmanager/firewall.py
Added SMTPS and On-Demand Mail Relay (used by Fetchmail, xODMR). Both of these are in the Fedora 20 /etc/services.
=> Added SMTPS and ODMR

backupdlg.ui, multiselectwidget.ui
Fix for bug: https://github.com/QubesOS/qubes-issues/issues/1467
=> Ensure list box resizes with window

qubesmanager/block.py
fixes QubesOS/qubes-issues#2156
=> fix TypeError in check_if_serves_as_backend

qubesmanager/backup.py
=> Sort items in Backup selection dialog

Makefile, about.ui, informationnotes.ui, mainwindow.ui, networknotes.ui, qubesmanager/about.py, qubesmanager/informationnotes.py, qubesmanager/main.py, qubesmanager/networknotes.py, qubesmanager/qvm_about.sh, qubesmanager/qvm_net.py, rpm_spec/qmgr.spec
QubesOS/qubes-issues#1431 
Functional (= not pretty) further information, and simple view of Qubes networking from About Menu
=> Add extended information and Network diagram to Manager

qubesmanager/main.py
https://github.com/QubesOS/qubes-issues/issues/2562
I'd meant to do this a while ago...
=> Proper fix for #2562

qubesmanager/main.py
Fixes https://github.com/QubesOS/qubes-issues/issues/2637
=> Use app instead of self for .tr() outside QObject

qubesmanager/backup.py, qubesmanager/log_dialog.py, qubesmanager/main.py, qubesmanager/restore.py
Fixes https://github.com/QubesOS/qubes-issues/issues/2637
=> Add more missing unicode()s around .tr()s

qubesmanager/table_widgets.py
See Jul 1 post at https://github.com/QubesOS/qubes-issues/issues/911
Overall its more readable and works with different palettes.
=> Progress bar can match light or dark palette

qubesmanager/main.py
Hello!
The commit included in this pull request aims to fix QubesOS/qubes-issues#2438.
Please see the commit message for further details.
This commit cleanly applies to the `release3.2` branch, and it would be nice to cherry-pick the commit to that branch.
=> Do not abort VM restarts due to inconsistent info

qubesmanager/settings.py
Hello!
This pull request contains two minor fix commits for Qubes Manager.
These commits should apply cleanly to the `release3.2` branch as well, and it would be nice if they could be cherry-picked to that branch if they are merged to the master branch.
Thank you!
Vefa
=> Minor fixes

qubesmanager/settings.py, ui/settingsdlg.ui
Added two buttons to VM Settings window: 
- refresh available apps in Applications tab
- rename VM in Basic
=> Changes to VM Settings: refresh apps and rename VM

qubesmanager/create_new_vm.py, ui/newappvmdlg.ui
Reworked Create VM window
Redesigned for more logical flow; fixed problems with selecting
incompatible options.
fixes QubesOS/qubes-issues#1251
=> Create new VM GUI

qubesmanager/create_new_vm.py, qubesmanager/global_settings.py, qubesmanager/settings.py, qubesmanager/utils.py
Follow change introduced by https://github.com/QubesOS/qubes-core-admin-client/pull/29
And fix QubesOS/qubes-issues#3145
=> Use 'klass' attribute instead of object class

ui/settingsdlg.ui
Added a tooltip clarifying that changing firewall settings does not
affect existing connections.
fixes QubesOS/qubes-issues#2731
=> Added tooltip to better explain firewall settings

qubesmanager/table_widgets.py, qubesmanager/utils.py, ui/qubemanager.ui
* an error that did not format last backup date correctly
* issue with app.labels
* and renaming of 'size' to 'disk size' in qube-manager
fixes QubesOS/qubes-issues#3475
=> Bunch of fixes for 4.0

qubesmanager/qube_manager.py
fixes QubesOS/qubes-issues#3501
=> Fixed error on VM shutdown in Qube Manager

qubesmanager/qube_manager.py
fixes QubesOS/qubes-issues#3501
=> Once more to fix the vm shutdown bug in Qube Manager

qubesmanager/settings.py, qubesmanager/utils.py
Fixed two errors with VM settings:
- incorrect display of current virt mode
- incorrect display and setting of template
fixes QubesOS/qubes-issues#3517
=> Vm settings choice fixes

qubesmanager/settings.py
Fixed error in DispVM selection in VM settings
fixes QubesOS/qubes-issues#3565
=> Fixed incorrect default dispvm settings

qubesmanager/qube_manager.py
- improved refreshing
- clear cache when it's needed
- hopefully FINALLY a fix for the shutdown bug
fixes QubesOS/qubes-issues#3501
=> A bunch of Qube Manager fixes

qubesmanager/bootfromdevice.py
The window wasn't closing properly.
=> Boot from device window fix

qubesmanager/qube_manager.py
Yet another attempt at stomping this zombie monstrosity.
fixes QubesOS/qubes-issues#3570
=> Is this bug finally dead

qubesmanager/settings.py, ui/settingsdlg.ui
Simple "Apply" button.
fixes QubesOS/qubes-issues#3321
=> Added 'Apply' button to VM Settings

qubesmanager/backup_utils.py, qubesmanager/restore.py
Fix https://github.com/QubesOS/qubes-issues/issues/1859
Also needs a pull on qubes-core-admin
=> Fix UnicodeErrors with translations and Unicode path's when restoring backup

qubesmanager/qube_manager.py, ui/qubemanager.ui
fixes QubesOS/qubes-issues#3683
=> Added "Exit" option to Qube Manager

qubesmanager/qube_manager.py
Replaced them with a more flexible behavior or removed if they were
not actually necessary (and handled elsewhere).
fixes QubesOS/qubes-issues#3623
=> Fixed a bunch of useless asserts

qubesmanager/global_settings.py, ui/globalsettingsdlg.ui
Added "default dispvm" to Global Settings.
references QubesOS/qubes-issues#3688
=> Added default_dispvm to Global Settings

qubesmanager/backup_utils.py
GUI Restore (and backup) tool was unable to open file selection dialog in dom0.
fixes QubesOS/qubes-issues#3701
=> Fixed GUI Restore tool bug

Makefile, ui/globalsettingsdlg.ui
Improved text in global settings window and a small fix to makefile.
fixes QubesOS/qubes-issues#3732
=> Bugfix3732

qubesmanager/firewall.py
When all firewall rules are removed, qubes-vm-settings crashed trying to check if the last rule accepts or drops all packages. It is now verifies that there is a last rule.
Also, it is now properly verified that the last rule accept or drops all packages.
Associated stack trace:
```
----
line: last_rule = reversed_rules.pop(0)
func: get_firewall_conf
line no.: 227
file: /usr/lib/python3.5/site-packages/qubesmanager/firewall.py
----
line: conf = self.get_firewall_conf(vm)
func: set_vm
line no.: 308
file: /usr/lib/python3.5/site-packages/qubesmanager/firewall.py
----
line: model.set_vm(vm)
func: __init__
line no.: 111
file: /usr/lib/python3.5/site-packages/qubesmanager/settings.py
----
line: settings_window = VMSettingsWindow(vm, qapp, args.tab)
func: main
line no.: 1133
file: …
```
=> Settings window: do not crash when there is no firewall rule

qubesmanager/qube_manager.py, qubesmanager/table_widgets.py, ui/qubemanager.ui, ui/settingsdlg.ui
Hi
Here is a version running with dbus events except some status changes that are not notified (pause/resume, template updates, netvm changes...).
=> Dbus version

qubesmanager/firewall.py
Adding a nonexisting service will no longer add "any" service.
=> Fix for bug in VM Settings

qubesmanager/qube_manager.py, qubesmanager/settings.py, qubesmanager/table_widgets.py, qubesmanager/utils.py, test-packages/qubesadmin/backup/restore/__init__.py
Fixes to make pylint 2.0 stop complaining.
=> Changes to for pylint 2.0

qubesmanager/global_settings.py
fixes QubesOS/qubes-issues#4114
=>  Fixed problem with setting default_dispvm  and default_template to None in Global Settings 

qubesmanager/qube_manager.py, test-packages/qubesadmin/exc.py
It will hopefully fix QubesOS/qubes-issues#4163 .
references QubesOS/qubes-issues#4163
=> Fixed error with asynchronous handling of VM remove and VM halting

ui/settingsdlg.ui
The button was too wide and difficult to interact with.
=> Modified VM settings to make 'refresh apps' button clearer

qubesmanager/settings.py, ui/settingsdlg.ui
Added two buttons to enable/disable seamless mode
for windows qubes.
references QubesOS/qubes-issues#3585
references QubesOS/qubes-issues#4342
=> Added GUI for toggling of seamless mode for windows

qubesmanager/settings.py, rpm_spec/qmgr.spec.in
requires https://github.com/QubesOS/qubes-desktop-linux-common/commit/e26debfe97b7c252ab9e34611298745e135083c6
fixes QubesOS/qubes-issues#4383
=> Refresh Apps in vm settings now refreshes the vm and template both

qubesmanager/create_new_vm.py
private volume is now ignored
fixes QubesOS/qubes-issues#4045
=> Fixed behavior of Create Standalone VM based on template

qubesmanager/settings.py
According to changes in https://github.com/QubesOS/qubes-core-admin/pull/241/commits/4dc863101067ee66fa13c3e5d2c8e20d0d80eac8 ,
memory balancing is now handled not by a special service but by
magic value of 0 maxmem. Added handling thereof to VM Settings -
also, settings will store the last used maxmem value in
qubesmanager.maxmem_value feature.
fixes QubesOS/qubes-issues#4480
=> Changed handling of maxmem/memory balancing in VM Settings

qubesmanager/backup.py, qubesmanager/restore.py, ui/restoredlg.ui
A bunch of issues concerning the qubes-backup tool: incorrect Qt exit, honoring include_in_backups, more info about dom0_restore.
fixes QubesOS/qubes-issues#4677
fixes QubesOS/qubes-issues#4713
references QubesOS/qubes-issues#3975
=> Backup fixes

qubesmanager/settings.py
fixes QubesOS/qubes-issues#4745
=> Fix error on warning in Settings on Rename VM

qubesmanager/dsa-4371-update, qubesmanager/qube_manager.py, rpm_spec/qmgr.spec.in
Script by @HW42 slightly modified.
QubesOS/qubes-issues#4752
=> Apply DSA-4371 fix before launching updates

qubesmanager/settings.py, ui/settingsdlg.ui
When NetVM is set to something else than default_dispvm has set, a warning
icon appears.
=> Added warning when setting NetVM

qubesmanager/settings.py
fixes QubesOS/qubes-issues#4866
=> Fix bug with fixed bug in VM Settings

ui/restoredlg.ui
fixes QubesOS/qubes-issues#4873
=> Fixed text error in Restore GUI

qubesmanager/global_settings.py
the check-updates default was being incorrectly set
=> Fixed minor errors found when debugging feature settings

qubesmanager/qube_manager.py
Tested successfully in my dom0.
=> Set the window title when cloning a qube

qubesmanager/qube_manager.py, qubesmanager/table_widgets.py, ui/qubemanager.ui
- widgets were rewritten to have less duplicate code and make adding a new widget more straightforward
- a new widget that shows whether a VM is a DVM template was added
fixes QubesOS/qubes-issues#4912
=> Qube Manager widget update

qubesmanager/settings.py
fixes QubesOS/qubes-issues#4951
=> Fixed error in VM settings

qubesmanager/global_settings.py, qubesmanager/qube_manager.py, ui/qubemanager.ui
Fixes for a bunch of bugs discovered during test writing:
- incorrect check dom0 updates handling in Global Settings
- some unnecessary property setting in Global Settings
- no warning on attempts to clone a VM to an existing name in Qube Manager
- bug with hiding last visible column in Qube Manager
- protected Qube Manager from blowing up due to malformed settings file
- fixed logs menu contents in Qube Manager
=> Assorted fixes

qubesmanager/settings.py, ui/settingsdlg.ui
fixes QubesOS/qubes-issues#5050
=> Added Virtual DNS display to VM settings

qubesmanager/utils.py
Kernels are sorted with a rough algorithm, comparing groups of numbers
numerically, and names consisting of strings alphabetically.
fixes QubesOS/qubes-issues#5084
=> Sorted kernels in VM settings

qubesmanager/settings.py
fixes QubesOS/qubes-issues#4949
=> Cleaned up QThreads usage in VM Settings

qubesmanager/bootfromdevice.py
Now, when selecting a file fails for some reason
(lack of installed file manager, VM crashed on start,
anything), the user will get an error message.
references QubesOS/qubes-issues#5202
=> Fixed silent fail in Boot from File window

qubesmanager/utils.py, ui/settingsdlg.ui
Kernel sorting and wrong display for dispVM template.
fixes QubesOS/qubes-issues#5208
=> Minor bugfixes for VM settings

qubesmanager/firewall.py
Opening an existing FW rule resulted in an invalid port number.
=> Fixed bug with port numbers and services in VM settings

qubesmanager/create_new_vm.py, ui/newappvmdlg.ui
Tab contains a warning, provides_network checkbox,
install_system_after_creation checkbox, storage pool
and initial RAM.
references QubesOS/qubes-issues#5127
fixes QubeSOS/qubes-issues#5198
=> Added an Advanced tab to Create New Qube dialog

qubesmanager/firewall.py
Now, an error will not close the window, enabling
the user to correct any mistakes.
fixes QubesOS/qubes-issues#bugfix5234
=> Fixed new firewall rule window

qubesmanager/backup_utils.py
Return type of QFileDialog changed between PyQt4 and PyQt5.
fixes QubesOS/qubes-issues#5353
=> Fixed change in QFileDialog behavior in PyQt5

qubesmanager/settings.py, ui/settingsdlg.ui
No netvm warning will now show differently for VMs that don't provide
network and those that do.
=> Fixed VM settings warning labels

qubesmanager/backup.py, qubesmanager/backup_utils.py
Also removed unused settings.
fixes QubesOS/qubes-issues#5430
=> Fixed error in selecting backup directory in GUI backup

qubesmanager/global_settings.py
Incorrectly named variable caused crash on start.
=> Fixed bug with Global Settings

.tx/config, README.md, qubesmanager/i18n/qubesmanager_en.ts, qubesmanager/i18n/qubesmanager_es.ts
Corrected .tx/config file and added instructions on pulling/pushing translations
to transifex.
references QubesOS/qubes-issues#5410
references QubesOS/qubes-issues#3548
=> Fixed transifex integration

ui/globalsettingsdlg.ui
They got a bit out of hand with their size.
=> Resized Global Settings

ui/settingsdlg.ui
fixed bug introduced in https://github.com/QubesOS/qubes-manager/commit/67d3b1220b1fe235933f9c81e2dc6cdbffa363c9
fixes QubesOS/qubes-issues#5611
=> Fixed tab order

qubesmanager/tests/__init__.py, qubesmanager/tests/test_vm_settings.py
fixes QubesOS/qubes-issues#5694
=> Fixed bug in tests that leads to occassional timeouts on slow machines

qubesmanager/qube_manager.py, ui/qubemanager.ui
The action uses qvm-console-dispvm.
fixes QubesOS/qubes-issues#4544
=> Added "Open console" action to Qube Manager

qubesmanager/settings.py
- correct template values for DispVMs
- template for running VMs should not be changeable
fixes QubesOS/qubes-issues#5746
=> Corrected template logic for VM Settings

qubesmanager/qube_manager.py
No more silent errors - the user will get an error message.
fixes QubesOS/qubes-issues#5810
=> Better error handling for opening VM settings in Qube Manager

qubesmanager/backup.py, qubesmanager/qube_manager.py, qubesmanager/template_manager.py, qubesmanager/tests/test_backup.py, qubesmanager/tests/test_backup_utils.py, qubesmanager/tests/test_create_new_vm.py, qubesmanager/tests/test_global_settings.py, qubesmanager/tests/test_qube_manager.py, qubesmanager/tests/test_vm_settings.py
fixes QubesOS/qubes-issues#5849
=> Make sure Quamash uses correct PyQt version

qubesmanager/create_new_vm.py
Fixes https://github.com/QubesOS/qubes-issues/issues/5902
=> Don't reset template when changing type during qube creation

qubesmanager/settings.py
Now it can be anything up to pool size.
fixes QubesOS/qubes-issues#5890
=> Fixed max volume size in VM settings

ui/globalsettingsdlg.ui
fixes QubesOS/qubes-issues#5941
=> Added more description to Global Settings update repo settings

qubesmanager/qube_manager.py, qubesmanager/tests/test_qube_manager.py
fixes QubesOS/qubes-issues#5963
=> Fix incorrect Settings invocation in Qube Manager

.travis.yml, ci/requirements.txt, debian/control, qubesmanager/tests/__init__.py, qubesmanager/utils.py, rpm_spec/qmgr.spec.in
Fixes QubesOS/qubes-issues#5873
=> Replace quamash with qasync

qubesmanager/restore.py
fixes QubesOS/qubes-issues#6035
=> Fixed missing verbose error logging in Restore Backup

qubesmanager/bootfromdevice.py
fixes QubesOS/qubes-issues#6018
=> Fix Boot from Device error when no block devices were found

qubesmanager/qube_manager.py
requires https://github.com/QubesOS/qubes-core-admin-client/pull/161
references QubesOS/qubes-issues#6030
=> Warn if trying to change layout on unsupported vms in Qube Manager

qubesmanager/settings.py
fixes QubesOS/qubes-issues#6108
=> Fixed incorrect virtmode check (ignored PVH when it was the default)

ui/settingsdlg.ui
fixes QubesOS/qubes-issues#6247
=> Enable word wrap for kernel opts in VM settings

qubesmanager/backup.py, qubesmanager/qube_manager.py, qubesmanager/template_manager.py, qubesmanager/tests/test_backup.py, qubesmanager/tests/test_backup_utils.py, qubesmanager/tests/test_create_new_vm.py, qubesmanager/tests/test_global_settings.py, qubesmanager/tests/test_qube_manager.py, qubesmanager/tests/test_vm_settings.py
harvimt/quamash#124
Fixes QubesOS/qubes-issues#6409
Fixes QubesOS/qubes-issues#5849
=> QUQMASH_QTIMPL -> QUAMASH_QTIMPL

qubesmanager/qube_manager.py, test-packages/qubesadmin/exc.py
main PR: https://github.com/QubesOS/qubes-core-admin/pull/398
=> manager: Handle removal of VM during on_shutdown.

qubes-tools.menu
The other tools were added here: https://github.com/QubesOS/qubes-manager/commit/d26b693e4f68730bbdc3034be754c954f729a064
=> Add updater to Qubes Tools menu

qubesmanager/backup_utils.py
See commit messages.
Fixes QubesOS/qubes-issues#6851
=> Various fixes

ui/devicelist.ui
Laid out the widget components in an appropriate Grid layout.
fixes QubesOS/qubes-issues#2095
=> Fix resizing of Device List widget in VM settings

rpm_spec/qmgr.spec.in
=> spec: add BR make and update R pyqt5

qubesmanager/global_settings.py, ui/globalsettingsdlg.ui
fixes QubesOS/qubes-issues#7027
=> Fix overzealous Default NetVM sanity check

qubesmanager/settings.py
requires https://github.com/QubesOS/qubes-core-admin-client/pull/194
fixes QubesOS/qubes-issues#7039
=> Clear property cache in VM settings' apply

qubesmanager/settings.py
- fix random indentation mistake
- fix interactions with services tab
- fix incorrect feature used
- fix bool coercion
fixes QubesOS/qubes-issues#5298
=> Fix functioning of shutdown-idle checkbox in settings

qubesmanager/appmenu_select.py, qubesmanager/global_settings.py, qubesmanager/log_dialog.py, qubesmanager/qube_manager.py, qubesmanager/template_manager.py
Use context manager for handling files and some processes.
Better iterate over dicts and arrays.
=> Fix issues found by pylint

.pylintrc, qubesmanager/about.py, qubesmanager/backup_utils.py, qubesmanager/clipboard.py, qubesmanager/firewall.py, qubesmanager/global_settings.py, qubesmanager/log_dialog.py, qubesmanager/releasenotes.py, qubesmanager/restore.py
=> Fix issues found by pylint, and adjust about dialog for gui domain

qubesmanager/qube_manager.py
fixes QubesOS/qubes-issues#7338
=> Fix loading menu and toolbar state from settings

qubesmanager/qube_manager.py
Fix missing error catch and missing ctrl+f searchbox shortcut.
fixes QubesOS/qubes-issues#7278
fixes QubesOS/qubes-issues#7129
=> Misc qube manager fixes

qubesmanager/qube_manager.py
fixes QubesOS/qubes-issues#7362
=> Refresh VM state at connection established in manager

qubesmanager/backup.py
fixes QubesOS/qubes-issues#7366
=> Add class to VM list in Backup widget

qubesmanager/backup.py, qubesmanager/restore.py, ui/backupdlg.ui, ui/restoredlg.ui
fixes QubesOS/qubes-issues#7853
=> Make show password buttons in backup gui toggleable

qubesmanager/settings.py
fixes QubesOS/qubes-issues#7897
=> Add explanation why you can't use vm settings with AdminVMs

ui/backupdlg.ui, ui/restoredlg.ui
This should be at the start of all HTML documents, to avoid quirks mode.
=> Add missing <!DOCTYPE html>

qubesmanager/tests/test_global_settings.py
Change in display of none for kernel requires changing tests to match.
=> Fix tests for kernel settings

qubesmanager/backup.py, qubesmanager/bootfromdevice.py, qubesmanager/global_settings.py, qubesmanager/log_dialog.py, qubesmanager/restore.py, qubesmanager/settings.py
fixes QubesOS/qubes-issues#7908
=> Add minimize/maximize buttons to manager tools

qubesmanager/settings.py
Now it's always 'Refresh applications'
fixes QubesOS/qubes-issues#8053
=> Fix capitalization inconsistency in VM settings

Makefile, debian/install, qubes-template-switcher.desktop, rpm_spec/qmgr.spec.in
Also added qvm-template-gui to menu as Template Manager
fixes https://github.com/QubesOS/qubes-issues/issues/6504
=> Rename old Template Manager to Template Switcher

qubesmanager/global_settings.py
fixes QubesOS/qubes-issues#8152
=> Use qrexec.client.call instead of reinventing it

qubesmanager/qube_manager.py
fixes QubesOS/qubes-issues#8382
=> Restart should be possible for persistent dispvms

qubesmanager/qube_manager.py
To avoid too big a system load, the update will happen:
- every 5 minutes for running qubes
- on qube state change (running -> transient -> halted etc.)
fixes QubesOS/qubes-issues#6053
=> Update size on disk in Qube Manager occassionally

qubesmanager/settings.py
after QubesOS/qubes-core-admin/pull/579
https://github.com/QubesOS/qubes-issues/issues/4626
=> update to new device API

qubesmanager/qube_manager.py
Allowing hyphen (dash, minus sign, ASCII 45, '-') in custom labels
=> Allow Hyphen character in custom labels

qubesmanager/i18n/qubesmanager_en.ts, qubesmanager/i18n/qubesmanager_es.ts, qubesmanager/template_manager.py, ui/templatemanager.ui
fixes: https://github.com/QubesOS/qubes-issues/issues/9298
=> Rename the Window title of old Template Manager to Template Switcher

qubesmanager/qvm_template_gui.py
The current Template Manager Window does not have any icon set
=> Loading Template Manager (qvm-template-gui) Window Icon

qubesmanager/qube_manager.py
Fixes: https://github.com/QubesOS/qubes-issues/issues/4581
=> Visually indicate unsupported Templates & StandaloneVMs in Qube Manager

qubesmanager/i18n/qubesmanager_es.ts, qubesmanager/qube_manager.py, qubesmanager/tests/test_qube_manager.py, qubesmanager/tests/test_vm_settings.py, ui/qubemanager.ui
Fixes: https://github.com/QubesOS/qubes-issues/issues/8872
=> Qube Manager: Replace "IP" with "IP Address"

qubesmanager/multiselectwidget.py
fixes: https://github.com/QubesOS/qubes-issues/issues/8836
=> Enabling double-click for VM Settings -> Available Apps <> Menu Apps

qubesmanager/bootfromdevice.py
fixes: https://github.com/QubesOS/qubes-issues/issues/9344
=> "Boot qubes from CD-ROM" shouldnt show the same qube as source

qubesmanager/settings.py, ui/settingsdlg.ui
fixes: https://github.com/QubesOS/qubes-issues/issues/7217
=> Disable "Disposable template" checkbox for non-AppVMs

qubesmanager/settings.py
Fixes: https://github.com/QubesOS/qubes-issues/issues/8685
As a side note, I am a new user of Qubes, so far I am very happy :)
I was not able to write a new test for this though as I had some errors running the test suite (related to dbus events) and I could not find online or in the readmes how to setup the environment for development.
=> Fix crash on VM settings for a VM with temporary unlocked FW

qubesmanager/utils.py, ui/qubemanager.ui
fixes: https://github.com/QubesOS/qubes-issues/issues/7255
=> Improve qubemanager Toolbar on smaller screens

qubesmanager/restore.py
Related: https://github.com/QubesOS/qubes-issues/issues/9387
Also adding option to go to next page on Enter in password field
=> Enable debugging for qubes-restore

qubesmanager/utils.py, ui/settingsdlg.ui
fixes: https://github.com/QubesOS/qubes-issues/issues/8889
=> Use GiB & MiB for private & system storage sizes

qubesmanager/qube_manager.py
fixes: https://github.com/QubesOS/qubes-issues/issues/9398
=> Show no IP for non-networked qubes

qubesmanager/qube_manager.py, ui/qubemanager.ui
fixes: https://github.com/QubesOS/qubes-issues/issues/8871
=> Add Ctrl+Q=exit, Ctrl+N=New qube, Home & End keys

qubesmanager/common_threads.py, qubesmanager/template_manager.py
- improved behavior on double-click
- improved behavior on OK (progress dialog)
- no auto-close on OK
fixes QubesOS/qubes-issues#7639
=> Fixes to Template Switcher

qubesmanager/i18n/qubesmanager_en.ts, qubesmanager/i18n/qubesmanager_es.ts, qubesmanager/qvm_template_gui.py, ui/newappvmdlg.ui, ui/settingsdlg.ui
fixes: https://github.com/QubesOS/qubes-issues/issues/7889
=> Use MiB & GiB (binary size) in Qube Manager

qubesmanager/qube_manager.py, ui/qubemanager.ui
fixes: https://github.com/QubesOS/qubes-issues/issues/8663
=> Option to show only `user` qubes in Qube Manager

qubesmanager/qube_manager.py
fixes: https://github.com/QubesOS/qubes-issues/issues/9029
=> Add `skipped` label to VMs excluded from updates

qubesmanager/qvm_template_gui.py
If upgrade comes from different repository than the installed template, show the repository in description.
=> Template Manager GUI: better info for upgradeable templates

qubesmanager/common_threads.py
=> Fix cloning from non-default to default pool

qubesmanager/i18n/qubesmanager_en.ts, qubesmanager/i18n/qubesmanager_es.ts, qubesmanager/restore.py
=> Update the location of partial restores in error message

qubesmanager/settings.py
fixes QubesOS/qubes-issues#8677
=> Stop CTD on failure to set seamless mode

qubesmanager/backup.py, qubesmanager/qube_manager.py, qubesmanager/qvm_template_gui.py, qubesmanager/restore.py, qubesmanager/settings.py, qubesmanager/template_manager.py
Without this, generic Wayland icon will be shown
=> Show (Manager App) Icons for Wayland/KDE
