qubesmanager/settings.py
The "default NetVM" is usually the first created ProxyVM which is
set by qubes-core during its creation. [1] If there is no ProxyVM,
there is no "default NetVM". Therefore, creating an AppVM and
launching its settings dialog raised AttributeError, because
get_default_netvm method returned None.
This can be reproduced by installing QubesOS without creating VMs
by installer.
[1] https://github.com/QubesOS/qubes-core-admin/blob/master/core/qubes.py#L355
Fixes qubesos/qubes-issues#1008
=> Checking whether the "default NetVM" exists

settingsdlg.ui
The services tab says that unlisted services will, "follow default VM's settings."  When I happened to see this, I was confused: which default VM?  The default NetVM?  The default TemplateVM?
After some investigating in this repo and in 000QubesVm.py, I've come to understand that they simply take on *default* values, not the values from some *default VM*.
If this is not correct, and this request should be rejected, the language should definitely still be clarified!
=> Clarify language in services tab

qubesmanager/main.py
IMO it is too easy to accidentally delete the wrong VM if you use lots of short-term (but longer than disposable) VMs and have built muscle memory of just clicking "Ok" in the deletion confirmation box.
This patch requires you to type the full name of the VM, inspired by repo deletion confirmation on GitHub.
The confirmation box looks like this:
And if you type it wrong, you get this:
=> Require typing name of VM to remove

mainwindow.ui, qubesmanager/main.py
Example:
Some UX person (@bnvk?) might want to improve the placement or something, idk, but it's a HUGE usability improvement as-is for me, and likely anyone else who has 50+ VMs.
=> Implement searching for VMs in qubes-manager

mainwindow.ui
Triggered in standard Qt way with Alt+X to open the menu, and the underlined letter to perform that action.
Example (`Alt+M - N` to create new VM, `Alt+M - K` to Kill selected, etc.):
=> Add keyboard shortcuts for manager menu items

qubesmanager/log_dialog.py
[Currently in gui-daemon/xside.c (only other holder of the lock):](https://github.com/QubesOS/qubes-gui-daemon/blob/95417c573d9b24269d50b3733164c3c9e390851c/gui-daemon/xside.c#L428-L435)
```
g->inter_appviewer_lock_fd = open("/var/run/qubes/appviewer.lock",
O_RDWR | O_CREAT, 0666);
...
/* ignore possible errors */
fchmod(g->inter_appviewer_lock_fd, 0666);
```
=> Make inter-appviewer lock permissions consistent

qubesmanager/clipboard.py, qubesmanager/log_dialog.py, qubesmanager/main.py, rpm_spec/qmgr.spec
Ctrl+Shift+C would be preferable, but is quite difficult to do safely,
and this method seems like a reasonable security/UX compromise.
Discussed in:
- https://groups.google.com/forum/#!topic/qubes-devel/4_x7Su21i9o
- https://github.com/QubesOS/qubes-issues/issues/2438#issuecomment-261704575
Fixes https://github.com/QubesOS/qubes-issues/issues/2450
=> Implement "Copy Dom0 clipboard" tray menu item

qubesmanager/main.py
Entering non-ascii characters (e.g. "ą") in search
causes an UnicodeEncodeError. This is a quick fix.
Fixes QubesOS/qubes-issues#2562
=> Fix for UnicodeEncodeError in search

qubesmanager/main.py
Closes QubesOS/qubes-issues#2605
=> Turn on NetVM view in Manager by default. CPU column off.

backupdlg.ui
I had someone tell me IRL that they thought the fact that it still asked for a password when "Encrypt backup" was unchecked was a bug. This is not the case, so explain why.
I think this wording is more user-friendly than "also used for an HMAC" or such.
Fixes https://github.com/QubesOS/qubes-issues/issues/2365
=> backups: Explain why passwords are always required

qubesmanager/main.py
This gets around #2693 GUI update not running with vm-sudo enabled.
https://github.com/QubesOS/qubes-issues/issues/2693
=> Run InstallUpdatesGUI service as root

qubesmanager/clipboard.py, qubesmanager/main.py
QubesOS/qubes-issues#2825
Shows size in bytes if less than one KiB: 
> Copied **40 bytes** to the clipboard.
Shows size in bytes and units (up to GiB), rounded to one decimal place, if more than one KiB: 
> Copied **1904 bytes (1.9 KiB)** to the clipboard.
Are there any translation considerations for 'bytes'?
=> Show size of current inter-VM clipboard in Ctrl-Shift-C notification

globalsettingsdlg.ui, qubesmanager/backup.py, qubesmanager/clipboard.py, qubesmanager/global_settings.py, qubesmanager/main.py, qubesmanager/qvm_net.py, qubesmanager/restore.py, rpm_spec/qmgr.spec
updated globalsettings window with qubes 4.0 API, updated qubesmanager to compile under python3.
notes: qvm_net.py has been moved to a weird new location; to run globalsettings window use:
`python3 -m qubesmanager.global_settings`
=> New api for globalsettings & python3 for qubesmanager

qubesmanager/utils.py, ui/settingsdlg.ui
Renamed "NetVM" to "Networking" and to clear up any possible
misunderstanding, renamed "none" to "(none)" in the appropriate dropdown.
Fixes QubesOS/qubes-issues#1763
=> Rename NetVM to Networking in vm-settings

qubesmanager/bootfromdevice.py
Fixes missing cast to string in boot from cdrom tool.
fixes QubesOS/qubes-issues#3113
=> Fixed issue#3113 - boot from cdrom

qubesmanager/firewall.py, qubesmanager/settings.py, ui/newfwruledlg.ui, ui/settingsdlg.ui
VM Settings - Firewall Tab modifications
* changed underlying code to use Qubes 4.0 firewall API
* changed tab to handle only two basic situations: allow all outgoing connections and block all, with an optional whitelist and an option to allow all for a limited period of time
* removed 'allow DNS' and 'allow ICMP' checkboxes
=> Firewall settings

qubesmanager/firewall.py
Fixed bug that led to correct firewall configuration not being
recognized by GUI VM Settings.
fixes QubesOS/qubes-issues#3289
=> Fixed bug with firewall GUI settings

qubesmanager/settings.py, ui/settingsdlg.ui
Enabled Firewall tab even when there's no working netvm or the netvm
doesn't support qubes-firewall. An appropriate warning label and message
are shown in both cases.
fixes QubesOS/qubes-issues#3290
=> Enabled Firewall config without a netvm

qubesmanager/bootfromdevice.py
Fixes to boot-from-device GUI:
- fixed error with missing import
- added a warning if the VM is already running
- replaced 'VM' with 'qube' for consistency
fixes QubesOS/qubes-issues#3421
=> Boot gui fix

qubesmanager/settings.py
When init page was 'firewall', the tool incorrectly displayed warnings about wrong firewall vm configuration, without actually checking if they should be displayed.
=> Fixed minor error in VM Settings

qubesmanager/settings.py, ui/settingsdlg.ui
Somebody should review this from a UX perspective.
AFAICS there's no way to get the default value of a VM property. So I hard coded the default value for `virt_mode`.
=> Add handling for virt_mode including PVH mode

qubesmanager/device_list.py, qubesmanager/settings.py, rpm_spec/qmgr.spec, ui/devicelist.ui, ui/settingsdlg.ui
The button is in 'devices' tab of VM settings; it allows the user to
select which devices should have 'no-strict-reset' enabled and tells
the user not to change this setting if there are no errors.
(Also, there are some minor formatting fixes, because pylint was unhappy)
fixes QubesOS/qubes-issues#3205
=>  Added 'configure no strict reset for PCI devices' button 

qubesmanager/qube_manager.py, qubesmanager/table_widgets.py, ui/qubemanager.ui
Bunch of fixes for 4.0:
- fixed 'qube' spelling in Qube Manager
- Qube Manager refreshes after settings are closed
- Qube Manager columns are resizeable and the last one stretches to fill available space
=> Typos and minor fixes

ui/backupdlg.ui
pending discussion about whether we should save password in base64, please do not merge yet.
fixes QubesOS/qubes-issues#3500
=> Added warning to backup gui that password is saved in plain text.

qubesmanager/create_new_vm.py
Virt mode was forcibly set to HVM. Now, the virt mode is left as default,
unless a standalone VM with system installed from elsewhere is selected.
fixes QubesOS/qubes-issues#3515
=> Fixed error in creating new VMs from GUI

ui/settingsdlg.ui
* Better spacing for higher DPIs (enforce larger margin between groupbox title and contents
* Added a tooltip to clarify what default/not default means when selecting networking.
references QubesOS/qubes-issues#2211
references QubesOS/qubes-issues#3567
=> Bunch of UI improvements

qubesmanager/backup.py
Incorrect targetVM display - dom0 was not included, and the code
erroneously assumed that not only it is included, but also it's always
the first in the dropdown. No more assumptions.
fixes QubesOS/qubes-issues#3594
=> Fixed bug 3594

qubesmanager/global_settings.py, qubesmanager/utils.py, ui/globalsettingsdlg.ui
A bunch of minor fixes for errors discovered in testings:
- updatevm, clockvm, default netvm couldn't be set to None in global settings
- default template and kernel pickers were made completely from scratch, instead of using prepare_choice from utils
- check-dom0-updates wasn't working
- replaced check_for_updates checkbox with buttons to change state of all vms
=> Fixes feb2018

ui/globalsettingsdlg.ui
In lieu of bigger overhaul/processing policy files in
VM Settings, a bit of explanation for updateVM in Global
Settings and a change of name from UpdateVM to Dom0 Update VM
there. This is quick fix solution, pending a better
one when (hopefully) we get some better API for
interacting with policies.
references QubesOS/qubes-issues#3412
=> Minor textual update for Global Settings

qubesmanager/qube_manager.py
The window should first display itself, and then get gradually filled with VMs
(more user friendly, less annoying than waiting for something, anything
to appear).
Also fixed a dumb bug with double refreshing and a useless variable.
fixes QubesOS/qubes-issues#3719
=> Less horrible Qube Manager loading

qubesmanager/qube_manager.py, test-packages/qubesadmin/exc.py
In some cases, when the user waited some time before force-killing a VM,
it could be already dead.
fixes QubesOS/qubes-issues#3730
=> Check if VM needs killing before murdering it

qubesmanager/table_widgets.py
After fixing another bug, update status for a VM was not
initialized correctly.
fixes QubesOS/qubes-issues#3745
=> Fix for updates-available in qube-manager

qubesmanager/qube_manager.py
Made Qube Manager params consistent with other manager
tools (first Qt, then Qubes).
=> Tiny fix for Qube Manager params

qubesmanager/settings.py
Whenever Enter was pressed, the Settings window
closed and applied changes, which was very unintuitive
especially in case of Services tab.
references QubesOS/qubes-issues#3891
=> Fixes unwanted behavior in VM settings

qubesmanager/qube_manager.py, qubesmanager/settings.py, qubesmanager/table_widgets.py
I think this way is pretty overloaded. I would prefer catching the exception on main handle_exception(), check if the VM was removed and if yes, ignore it. Maybe I should check if the VM was removed before pass the exception but I am not sure about how to do it. At least I catch only the affected exception but it could mean another errors.
I also fixed two minor things:
- 'StandaloneVM's were not checked for updates. It stills missing checking for dom0 updates, how are them notified?
- the settings window was closed on renaming regardless the name is already in use.
=> Fix errors when a VM is renamed or two are fast deleted.

qubesmanager/log_dialog.py, rpm_spec/qmgr.spec.in, setup.py
Log dialog viewer is now also available as a separate tool (introduced
to simplify displaying logs in the qui-domains tool)
Added entry point and main() to enable using log viewer as a separate tool.
Includes a minor fix for error that occurred with large log files due to changes
in Python 3.
=> Log dialog separate

qubesmanager/qube_manager.py
Instead of generic menu with almost everything grayed-out, now
context menu for dom0 has only Global Settings, Logs and update.
references QubesOS/qubes-issues#1382
fixes QubesOS/qubes-issues#1165
=> Modified Qube Manager menu for dom0

qubesmanager/qube_manager.py, qubesmanager/table_widgets.py
Hi,
I cached all the variables used in _lt_ funcs so they don't need to access vm object. This way all columns sort as fast as the 'name' column in previous version.
As a side effect, _lt_ functions don't need try/except anymore and I moved all them to just one on VmRowInTable.update(), it looks better and probably fix some unknown similar problem.
=> Sort performance boost

qubesmanager/global_settings.py
A user should not be able to set a TemplateVM as an UpdateVM or ClockVM
in Global Settings.
fixes QubesOS/qubes-issues#1831
=> Remove templates from listing in UpdateVM and ClockVm in Global Settings

qubesmanager/qube_manager.py
Small fix to Qubes Manager to open the context menu slightly to the
right of the mouse to avoid accidental clicks. Originally created by
@unman , ported to 4.0 and including changes to context menu from
pull request#100.
Depends on https://github.com/QubesOS/qubes-manager/pull/100 .
fixes QubesOS/qubes-issues#1911
=> Offset context menu in Manager to avoid accidental clicks (R4.0)

ui/qubemanager.ui
Adds an explanatory (and slightly cautious, with a big EXPERIMENTAL
at the end) tooltip to the Pause action in Qube Manager.
references QubesOS/qubes-issues#1855
references QubesOS/qubes-issues#2211
=> Add explanatory tooltip to Pause in Qube Manager

qubesmanager/backup.py, ui/backupdlg.ui
A simple checkbox to turn off the computer after backup finishes
successfully. It is off by default and must be switched on every time
(unexpected system shutdowns are a huge pain, much more problematic
than forgetting to shut down can be).
fixes QubesOS/qubes-issues#2039
=>  Add option to turn off computer after backup to Backup GUI 

qubesmanager/main.py
Instead of killing only one thread, now SIGINT will correctly
exit the entire app.
fixes QubesOS/qubes-issues#1682
=> Correct handling for SIGINT in Qubes Manager

qubesmanager/main.py
Small fix to Qubes Manager to open the context menu slightly to the
right of the mouse to avoid accidental clicks. Originally created by
@unman , ported to 3.2 branch.
references QubesOS/qubes-issues#1911
closes https://github.com/QubesOS/qubes-manager/pull/31
=> Offset context menu in Manager to avoid accidental clicks (R3.2)

qubesmanager/main.py
On some occasions (e.g., when restarting) Qubes Manager would try to
start a VM twice, and threw an error. Removed the assertion and instead
just happily accept that there's nothing to do when starting a running
VM.
fixes QubesOS/qubes-issues#2362
=> Fixed bug with starting a running VM in Qubes Manager

settingsdlg.ui
Added an explanatory tooltip for NetVM for DispVM field in Settings GUI.
fixes QubesOS/qubes-issues#2379
=> Added tooltip to NetVM for DispVM in Settings GUI

qubesmanager/main.py
Using "attach block device" to dom0 was causing total failure of
Qubes Manager. The menu is now disabled for dom0.
fixes QubesOS/qubes-issues#2733
=> Disable block device attach menu in Qubes Manager for dom0

qubesmanager/create_new_vm.py, qubesmanager/qube_manager.py, qubesmanager/settings.py
VM name validation in various places in Manager did not allow a
perfectly legal '_' character.
references QubesOS/qubes-issues#2422
=> Fixed VM name validation in GUI tools (Create VM, Settings, Manager) (R4)

qubesmanager/table_widgets.py
When a VM has netvm set to 'default', now Qube Manager will display
'(default)' in front of the netvm's name.
references QubesOS/qubes-issues#3567
=> Make 'NetVm' column in Qube Manager clearer with regars to defaults

qubesmanager/settings.py, ui/settingsdlg.ui
Added a list of suggested services to the Services tab in VM Settings.
The list is drawn from man qvm-services (manually, not automatically).
fixes QubesOS/qubes-issues#3891
=> Add a list of Suggested Services to VM settings

qubesmanager/create_new_vm.py, qubesmanager/main.py, qubesmanager/settings.py
VM name validation in various places in Manager did not allow
perfectly legal otherwise '_' and '.' characters.
references QubesOS/qubes-issues#2422
fixes QubesOS/qubes-issues#3301
=> Fixed VM name validation in GUI tools (Create VM, Settings, Manager) (R3.2)

qubesmanager/utils.py
Kernel set to 'None' was incorrectly displayed as 'default'.
fixes QubesOS/qubes-issues#4043
=> Fixed incorrect kernel display in VM settings

qubesmanager/qube_manager.py
Qube Manager will now remember its size from last time it was run, and
also it will no longer force itself to appear at top left corner of
the screen.
fixes QubesOS/qubes-issues#4049
=> Make Qube Manager remember its size from last time

qubesmanager/qube_manager.py, qubesmanager/restore.py, qubesmanager/settings.py, qubesmanager/utils.py, test-packages/qubesadmin/utils.py
Added the following reactions to VM dependencies in GUI tools:
- Qube Manager will inform the user why they cannot delete a VM (which
properties of which VMs [or global] are using the VM)
- Settings window will try to intelligently rename VMs (change
properties to the new name, if possible, and inform the user what went
wrong if not)
- Settings window will inform the user why they cannot delete a VM
Also, renaming VM from Settings launched from Qube Manager will
refresh the VM list through a horrible hack, to be replaced by a neater
Admin API solution in some near future.
depends on QubesOS/qubes-core-admin-client@ca848ca
fixes QubesOS/qubes-issues#3992
fixes QubesOS/qubes-issues#3993
fixes QubesOS/qubes-issues#3892
fixes QubesOS/qubes-issues#3499
=> Handling VM dependencies in GUI tools

qubesmanager/qube_manager.py
Columns were resizing incorrectly (with too large minimums).
fixes QubesOS/qubes-issues#4002
=> Fixed column widths in Qube Manager

qubesmanager/qube_manager.py
On change of template Vm status, qube Manager errored
out. It no longer does that.
=> Fixed a small bug with Qube Manager status refresh

qubesmanager/qube_manager.py
Fixes error that can occur when VM-removed and VM-changed
events fire too closely together.
fixes QubesOS/qubes-issues#4317
=> Fix error on refresh when a VM has vanished

qubesmanager/settings.py, ui/settingsdlg.ui
For some reason, they were not being displayed at all. Now fixed.
fixes QubesOS/qubes-issues#4188
=> Fixed kernelopts in VM settings

qubesmanager/log_dialog.py
Unicode characters caused an error.
fixes QubesOS/qubes-issues#2751
=> Fixed error in displaying VM log when unicode characters were encountered

qubesmanager/qube_manager.py
In some cases (when a VM quickly appears and disappears)
the events were handled in a wrong order.
fixes QubesOS/qubes-issues#4414
=> Fix error in qube manager

qubesmanager/create_new_vm.py
To avoid conflict with scripts that make whonix magic,
if the user selects default netvm, we do not set any  netvm and
trust the create_vm method to properly set it as default appropriate
for the given template.
fixes QubesOS/qubes-issues#1954
=> Changed to not force default netvm in Create New VM

qubesmanager/template_manager.py
DispVMs are now correctly excluded from Template Manager.
fixes QubesOS/qubes-issues#4704
fixes QubesOS/qubes-issues#4703
=> Fixed DispVM handling in Template Manager

qubesmanager/qube_manager.py, qubesmanager/table_widgets.py
Fixed label not updating and changed the update process to be more selective: now, the event
that fired the update is examined and only matching widgets are updated.
fixes QubesOS/qubes-issues#3675
=> Fix to updating Qube Manager

qubesmanager/global_settings.py
This pull request has a dependency on the following one: https://github.com/QubesOS/qubes-core-admin/pull/249
=> global_settings: Use MiB, not M as the unit

ui/backupdlg.ui, ui/devicelist.ui, ui/globalsettingsdlg.ui, ui/newappvmdlg.ui, ui/newfwruledlg.ui, ui/restoredlg.ui, ui/settingsdlg.ui
Fixed tab order in multiple widgets: Backup, Global Settings,
Create New Qube, Settings, Restore.
fixes QubesOS/qubes-issues#4746
=> Tab Order Cleanup

ui/backupdlg.ui
Added information about where the profile with plaintext password is
actually located.
fixes QubesOS/qubes-issues#4777
=> Added more information to GUI Backup Tool

qubesmanager/settings.py, ui/settingsdlg.ui
Added an 'Advanced' settings checkbox that allows the user to set a given
VM as template fo dispvms. It sets both the template_for_dispvms property
and the appmenus-dispvm feature - instead of delving into particulars
of how and which should be set, the user can just turn off the
whole setting if they want to make some changes in the vm and then turn
it on again.
fixes QubesOS/qubes-issues#4004
=> Added "set as dvm template" to VM settings

qubesmanager/settings.py
Changes in some fields (to be precise, drop-downs) were discarded
in VM Settings when changed after an 'Apply' and before an 'OK'.
fixes QubesOS/qubes-issues#4833
=> Fixed incorrect behavior after 'Apply' in Settings

qubesmanager/settings.py
when the currect VM is the same as the dvm_template, there should be no
warning
fixes QubesOS/qubes-issues#4844
=> Fixed error in detecting dvm-template having different NetVM

qubesmanager/settings.py
VM rename was incorrectly trying to display an error by itself and not
use QThreads embedded mechanism.
fixes QubesOS/qubes-issues#4843
fixes QubesOS/qubes-issues#4767
=> Fixed error in displaying error on VM Rename

qubesmanager/settings.py
Bug related to previous fixes to 'apply'; part of the code still
incorrectly assumed some attributes may not exist
fixes QubesOS/qubes-issues#4866
=> Fix bug with VM Settings

qubesmanager/backup.py
the Backup Qubes tool failed to allow user to exit correctly
after backup errored out in any way.
fixes QubesOS/qubes-issues#4885
=> fix incorrect behavior after backup error

qubesmanager/utils.py
Possibly due to changes in how services work,
the run_service_for_stdio was returning path with trailing
whitespace.
fixes QubesOS/qubes-issues#4921
=> Fixed minor error in Qubes Backup

qubesmanager/settings.py
PCI devices will now correctly be unmodifiable if the VM is running.
fixes QubesOS/qubes-issues#4933
=> Fixed device list behavior for a running VM in VM settings

qubesmanager/device_list.py, qubesmanager/settings.py
PCI devices are now handled as DeviceInfo objects, not (string,name) tuples;
furthermore, a device that no longer exists in the system can be
correctly removed via VM settings window (it is displayed as Unknown
device).
fixes QubesOS/qubes-issues#2789
=> Fixed device handling in VM settings widget

qubesmanager/qube_manager.py
In rare case (when the Qube Manager was reverted to an older version
that does not have a column on which it was last sorted) downgrading
Qube Manager could result in a crash on start.
=> Fix error on reverting Qube Manager to an older version

qubesmanager/common_threads.py, qubesmanager/qube_manager.py
Now success will not be accompanied by a 'warning'
icon.
fixes QubesOS/qubes-issues#4922
=> Fixed inconsisted icon in Qube Manager messages

qubesmanager/dsa-4371-update
kali /etc/debian_version is "kali-rolling".
debian-10 /etc/debian_version is "buster/sid".
kali-rolling is currently based on buster.
the qubes-manager check doesnt have a buster branch right now, but is matching that as */sid.
not really sure this is the right way to go (why are we not matching the "buster" part?), but this works-for-me for updating both debian-10 and kali templates.
=> treat kali-* as a variant of buster/sid

qubesmanager/create_new_vm.py
Changed the terms used in Create New VM Gui to the following:
-Qube based on a template (AppVM)
-Standalone qube
-Standalone qube copied from a template
references QubesOS/qubes-issues#4723
=> Made terminology in Create New VM GUI clearer

qubesmanager/qube_manager.py
If for any reason adding a VM failed, Qube Manager will attempt to add it on the next state event it receives.
references QubesOS/qubes-issues#5066
=> More safeguards for a VM that started in a weird way

qubesmanager/settings.py, ui/settingsdlg.ui
A simple checkbox in the 'Advanced' tab. Does not allow disabling
'provides_network' if the VM is in use as NetVM; instead, a tooltip
informs the user which VMs use it.
fixes QubesOS/qubes-issues#5079
=> Added 'provides network' checkbox to VM settings

ui/globalsettingsdlg.ui, ui/qubemanager.ui, ui/settingsdlg.ui
Replaced instances of "Default DispVM" and "Is DVM Template" with
more readable "Default Disposable VM Template" and "Disposable VM Template"
respectively. Added tooltips.
fixes QubesOS/qubes-issues#4935
=> Renamed DispVM and "Is DispVM template" for more readability

qubesmanager/create_new_vm.py
Minor pre-emptive fix for not-yet-existing "VM name lookup" issue
and a fix for incorrect defaults for standalone VMs not based on a
template
fixes QubesOS/qubes-issues#5203
=> Two fixes for Create New VM

qubesmanager/firewall.py, ui/newfwruledlg.ui
Now port will be displayed as port_number [(service name)]
, and not just service name. Also added a tooltip with explanation
of what can be put in the 'port/service' field, renamed
the field to 'Port/service' and added some examples of pure port
numbers to the drop down.
Also removed 'smtps' from the list of services because it was not in 
/etc/services and fixed parsing of port ranges.
fixes QubesOS/qubes-issues#5211
fixes QubesOS/qubes-issues#4766
=> Better handling of port/service names for VM settings

qubesmanager/global_settings.py, ui/globalsettingsdlg.ui
Screenshot:
Menu options provided:
* Stable updates
* Testing updates (security only)
* Testing updates
* Unstable updates
---
* ITL template updates
* ITL template updates (testing)
---
* (Community templates disabled)
* Community template updates
* Community template updates (testing)
I'll fix the TODO in the PR with the qrexec services and then delete the hack in this code. But since the rest of this is complete I figured I'd open a PR and get the ball rolling on code review.
Depends on QubesOS/qubes-core-admin-linux#48
Fixes QubesOS/qubes-issues#4550
=> Add UI for managing Qubes update repositories

qubes-backup-restore.desktop, qubes-backup.desktop, qubes-global-settings.desktop, qubes-qube-manager.desktop, qubes-template-manager.desktop, qubes-tools.directory, qubes-tools.menu, qubes-vm-create.desktop, rpm_spec/qmgr.spec.in
Added a menu directory with Qubes tools (to make them easier to find)
and also adds Qubes tools to XFCE settings manager.
Requires https://github.com/QubesOS/qubes-desktop-linux-xfce4/pull/14
=> Added menu position with Qubes Tools to XFCE Menu

Makefile, build-deps.list, qubesmanager/about.py, qubesmanager/appmenu_select.py, qubesmanager/backup.py, qubesmanager/backup_utils.py, qubesmanager/bootfromdevice.py, qubesmanager/clipboard.py, qubesmanager/common_threads.py, qubesmanager/create_new_vm.py, qubesmanager/device_list.py, qubesmanager/firewall.py, qubesmanager/global_settings.py, qubesmanager/informationnotes.py, qubesmanager/log_dialog.py, qubesmanager/multiselectwidget.py, qubesmanager/qube_manager.py, qubesmanager/releasenotes.py, qubesmanager/restore.py, qubesmanager/settings.py, qubesmanager/table_widgets.py, qubesmanager/template_manager.py, qubesmanager/utils.py, rpm_spec/qmgr.spec.in, ui/restoredlg.ui
Fixed dependencies, places where obsolete functions stopped working,
code fragments that started throwing warnings and an .ui file that
stopped being readable after the update.
=> Update Qt version used in qubesmanager to Qt5

qubesmanager/appmenu_select.py
The 'Comment' field will now be displayed as a tooltip in VM settings.
Requires https://github.com/QubesOS/qubes-desktop-linux-common/pull/12
references QubesOS/qubes-issues#5076
=> Add tooltip to application list in VM settings

qubesmanager/qube_manager.py, ui/qubemanager.ui
Just another column that shows the
contents of virt_mode property.
fixes QubesOS/qubes-issues#4702
=> Added virt mode column to Qube Manager

qubesmanager/settings.py
From the commit message:
> Qubes Manager seems to try to guarantee that 10\*init_mem is at
> least max_mem by automatically adjusting init_mem to max_mem/10 if
> inappropriate values are set. However, this may not guarantee that
> 10\*init_mem >= max_mem due to rounding errors. This change fixes
> these edge cases by basically rounding up the result of division
> by 10.
Background: I discovered the issue that this change is trying to fix when I had an unround `max_mem` value like 4096 and a too low `init_mem` value which was (probably) automatically set to another inadmissible value, ending up in an infinite loop of warning windows. In retrospective, I'm a bit puzzled because this shouldn't be a problem in that range as `/` is floating point division in Python 3, but I still think that …
=> Fix arithmetic in init/max mem ratio correction

qubesmanager/qube_manager.py
Qube Manager will now properly update displayed values for default_netvm and default_dispvm. Furthermore, 'default' value for default_dispvm will be correctly shown as default (vm name).
fixes QubesOS/qubes-issues#5328
=> Improved handling of global properties and default dispVM in Qube Manager

qubesmanager/qube_manager.py
Qube Manager columns did not resize correctly in Qt5.
fixes QubesOS/qubes-issues#5278
=> Fixed UI error

qubesmanager/settings.py
Currently while renaming VMs, the default text is empty "". This change modifies this default text to the original name of the VM.
This makes it a lot easier to make small changes to the name. The original name is also _selected_ by default, so replacing it entirely is also easily -- simply start typing the new name.
=> Show the previous VM name while renaming

qubesmanager/backup.py, qubesmanager/backup_utils.py, qubesmanager/bootfromdevice.py, qubesmanager/firewall.py, qubesmanager/global_settings.py, qubesmanager/qube_manager.py, qubesmanager/restore.py, qubesmanager/settings.py, qubesmanager/template_manager.py, qubesmanager/utils.py
File selection dialog in GUI backup was using an obsolete
(and possibly never working as intented) setReadOnly method.
Removed it, because it neither works nor is needed.
Moved loop handling, exception handling and program
running methods of the gui tools to the utils file.
Also some assorted fixes to make pylint stop complaining.
fixes QubesOS/qubes-issues#5348
fixes QubesOS/qubes-issues#5342
=> Several GUI fixes (mostly due to new pylint)

qubesmanager/backup.py, qubesmanager/qube_manager.py, qubesmanager/template_manager.py, qubesmanager/utils.py
Using QIcon object before initializing QApplication leads to
missing theme icons.
fixes QubesOS/qubes-issues#5354
=> Fixed incorrect QApplication start that led to missing icons

qubesmanager/backup.py, qubesmanager/global_settings.py, qubesmanager/tests/__init__.py, qubesmanager/tests/test_backup.py, qubesmanager/tests/test_backup_utils.py, qubesmanager/tests/test_create_new_vm.py, qubesmanager/tests/test_global_settings.py, qubesmanager/tests/test_qube_manager.py, qubesmanager/tests/test_vm_settings.py, ui/newappvmdlg.ui
A bunch of fixes for Qt5, including some fixes for features introduced after the switch.
Also a minor fix for issue found by tests.
And a fix for unhandled exception in backup.reject method that caused segfault when the backup
tool was ran without registering additional exception handler.
fixes QubesOS/qubes-issues#5395
=> Manager tests fixed for Qt5

ui/settingsdlg.ui
After some of recent fixes, tab order was no longer logical.
fixes QubesOS/qubes-issues#5356
=> Fixed tab order in VM Settings

ui/settingsdlg.ui
Made the tooltip warning of unexpected network access more descriptive.
fixes QubesOS/qubes-issues#5115
=> Reworded warning tooltip in settings

qubesmanager/settings.py
My story: while learning to use Qubes Settings and automatically switching between different tabs I used to get my train of thought interrupted all the time on the "Firewall rules" tab. If a qube does not have a netvm navigating to the tab brings up a popup. I hate popups. I'm sure I'm not alone in this. Usually there are less interruptive methods of communicating the same information to the user. Besides: this popup is redundant because you have already implemented one such method: a label that you show/hide as necessary. It's time to remove it.
=> Remove redundant popups from the firewall tab of Qubes Settings

qubesmanager/utils.py
Having kernels with certain names, `qubes-vm-settings` always crashed:
In the `__lt__` function for the class `KernelVersions`, if
`self.groups != other.groups`, but `self.groups == other.groups[0:n]` or
`self.groups[0:n] == other.groups` for some n, then at some point, one of
the two pieces to be compared will be `None`, which resulted in an
Exception when calling `isdigit`.
This is fixed in this commit by checking whether one of the pieces to be compared is `None` and handling this as a special case.
The same fix should apply to both master and release4.0, but I only tested it on release4.0.
=> Fix KernelVersion comparisons

qubesmanager/backup.py, test-packages/qubesadmin/exc.py
Shows a better error message when a given backup is already running.
fixes QubesOS/qubes-issues#5432
requires https://github.com/QubesOS/qubes-core-admin/pull/292
=> Add handling for backup in progress

qubesmanager/settings.py
Wrong variable name caused a crash on start
=> Fixed bug in VM Settings

qubesmanager/qube_manager.py, qubesmanager/tests/test_qube_manager.py, ui/settingsdlg.ui
On OpenQA 20 isn't enough to start a VM. Also make sure previous
shutdown has finished by using qvm-shutdown --wait.
VM needs to be started at least once to have active "logs" submenu. For
this reason, choose a running VM.
=> tests: fix startup timeout and looking for logs

ui/globalsettingsdlg.ui
Made it clear that it applies to memory _balancing_ not just memory.
fixes QubesOS/qubes-issues#5546
=> reworded memory balancing descriptions in Global Settings

qubesmanager/settings.py, qubesmanager/utils.py
VM Setting will now update (current) markers correctly after Apply.
fixes QubesOS/qubes-issues#5531
=> Fixed Apply behavior for VM Settings

qubesmanager/settings.py
Deleting qube will now show a Delete in Progress dialog box and
not exit QApplication before QThread finishes.
fixes QubesOS/qubes-issues#5515
=> Handle deleting in VM Settings without silent fails

qubesmanager/settings.py, ui/settingsdlg.ui
Slight change to layout of services tab, made it hopefully
less confusing. Dropdown will now list services supported by this
VM and its template, not just an assortment of hardcoded services.
=> Added handling for supported services to VM settings

qubesmanager/settings.py
Also fixed the init memory warning to only be shown for Linux qubes (it is
not necessary for other qubes)
fixes QubesOS/qubes-issues#5612
=> Fixed init memory warning being shown twice

qubesmanager/table_widgets.py
fixes QubesOS/qubes-issues#5661
=> Removed unnecessary 'needs restarting' icons for DisposableVMs in Qube Manager

qubesmanager/utils.py, ui/settingsdlg.ui
For sizes above 1 GB, the sizes of private image and root image will be displayed
as %.1f GB; smaller sizes will be displayed as %d MB.
fixes QubesOS/qubes-issues#5592
=> Changed display of image sizes in VM settings to GB when sensible

qubesmanager/settings.py
When a VM is not included in memory balancing, there is no point
(and it can be actively harmful via deception) in showing warnings
about init_mem and maxmem mismatch.
fixes QubesOS/qubes-issues#5306
=> Fixed incorrect memory checking in VM Settings

qubesmanager/appmenu_select.py, qubesmanager/settings.py, ui/settingsdlg.ui
On template change, qvm-appmenus is queried for changes in available apps.
If something is whitelisted and does not appear in the template, it is shown
in the list as "Application missing".
requires https://github.com/QubesOS/qubes-desktop-linux-common/pull/22
fixes QubesOS/qubes-issues#5796
=> Applications tab in settings now reacts to template change and missing entries

qubesmanager/tests/test_vm_settings.py
Incorrect maxmem value caused error.
fixes QubesOS/qubes-issues#5857
=> Fixed VM settings test

debian/install, qubesmanager/clone_vm.py, qubesmanager/common_threads.py, qubesmanager/qube_manager.py, qubesmanager/settings.py, qubesmanager/tests/test_clone_vm.py, qubesmanager/tests/test_create_new_vm.py, qubesmanager/tests/test_qube_manager.py, qubesmanager/tests/test_vm_settings.py, rpm_spec/qmgr.spec.in, setup.py, ui/clonevmdlg.ui
A simple GUI tool to enable cloning a VM to a different pool and changing the label. Qube Settings and Qube Manager now use it, too.
fixes QubesOS/qubes-issues#5127
fixes QubesOS/qubes-issues#5978
=>  Added a Clone Qube tool

qubesmanager/backup.py, qubesmanager/tests/test_backup.py, ui/backupdlg.ui
Instead of scary red warning, now a gentler information that only running qubes are
available is shown. It is also shown just under the destination VM dropdown,
making it easier to notice and interpret correctly.
fixes QubesOS/qubes-issues#5427
=> Modified warning shown when destination qube for backup is unavailable

qubesmanager/appmenu_select.py, qubesmanager/backup.py, qubesmanager/backup_utils.py, qubesmanager/bootfromdevice.py, qubesmanager/clone_vm.py, qubesmanager/create_new_vm.py, qubesmanager/global_settings.py, qubesmanager/qube_manager.py, qubesmanager/settings.py, qubesmanager/template_manager.py, qubesmanager/tests/test_global_settings.py, qubesmanager/tests/test_qube_manager.py, qubesmanager/utils.py, test-packages/qubesadmin/exc.py
All parts of qubesmanager package should now be as resilient as possible to missing permissions.
Within reason: if you can't list available labels, the create_new_vm tool will not be available etc.
fixes QubesOS/qubes-issues#5811
references QubesOS/qubes-issues#5403
=> Make qubesmanager resistant to missing permissions

ui/qubemanager.ui
Instead of tiny buttons, now Qube Manager will have bigger buttons and text underneath.
Furthermore, Pause gets renamed to Emergency pause for clearer communication.
references QubesOS/qubes-issues#5993
=> Modified Qube Manager toolbar to be more readable and added Emergency Pause

qubesmanager/settings.py, ui/settingsdlg.ui
When maxmem is set to over 10x initmem, Settings will now
show a warning label and not interfere with user-provided values.
The only case in which they will interfere is maxmem<initmem.
fixes QubesOS/qubes-issues#6016
=> Less intrusive max mem / init mem warning  in VM Setting

qubesmanager/settings.py, test-packages/qubesadmin/exc.py, ui/settingsdlg.ui
It is disabled if the service is unavailable and displays information
about how to enable it if it is unavailable.
references QubesOS/qubes-issues#5298
=> shutdown-when-idle gets its own checkbox in VM settings

qubesmanager/qube_manager.py, ui/qubemanager.ui
Hi, here is a first approach for fix: https://github.com/QubesOS/qubes-issues/issues/4529
It is very simple,  what is selected is being shown. Maybe we could discuss if network or templates VM's should be hidden from running.
I can add or remove some. By default all checkboxes are enabled.
=> bring back "Show/Hide inactive VMs" button

qubesmanager/qube_manager.py, ui/qubemanager.ui
Hi,
I've just added an action for hide the text on buttons and restore the appearance of R4.0.
Fixes: https://github.com/QubesOS/qubes-issues/issues/6166
=> Compact View

qubesmanager/log_dialog.py, qubesmanager/qube_manager.py, qubesmanager/utils.py, ui/logdlg.ui, ui/qubemanager.ui
Not very fashion but it saves a lot of clicks if you want to see many log files from one (or more) qubes.
Probably a list should be a better solution than buttons.
=> Multiple file log dialog

qubesmanager/qube_manager.py
It was really simple thanks to model/view architecture.
I tried to center the checkbox on the column but it will require to subclass ItemDelegate or similar. Maybe it would be just fine with a short column header text (e.g. "Inc. in Backup") or using two lines instead one.
=> Use checkbox for 'Include in Backup' column

qubesmanager/create_new_vm.py
Adds TemplateVM and DisposableVMs to the Create New Qube dialog.
Changes:
- Rewording of VM class dropdown to make more sense in context
- Added none to template rather than having a separate type for empty
- Adds TemplateVM and DisposableVM
- Adds dynamic updating of the template list depending on the selected VM class.
Considerations before merging:
- Is the use of in acceptable? (line 194)
- Is the dynamic updating of the template dropdown a reasonable solution?
- Does anything need to be updated on the translation side?
=> Added template and dispvm to create dialog

qubesmanager/settings.py
Fixed a spelling mistake in a warning message when trying to directly connect a TemplateVM to the network.
=> Fix spelling mistake in warning message

qubesmanager/log_dialog.py
instead of only the first one.  That caused argv[1] to be iterated over,
meaning that LogDialog would see it as a list of one-character
filenames.  Hilarity ensued.
=> Pass the command line arguments to LogDialog

qubesmanager/settings.py
Resolves QubesOS/qubes-issues#6592.
Qube Manager currently shows a security warning when changing the NetVM of TemplateVMs.
This warning is generally useful in other cases, but not when disabling networking;
for example changing from from "default" to "none".
In this commit, I introduce a change to not warn when disabling networking, by setting NetVM to None.
=> Avoid spurious warnings when setting NetVM

qubesmanager/about.py, qubesmanager/bootfromdevice.py, qubesmanager/create_new_vm.py, qubesmanager/informationnotes.py, qubesmanager/qube_manager.py, qubesmanager/releasenotes.py, qubesmanager/settings.py, qubesmanager/template_manager.py, qubesmanager/utils.py, ui/bootfromdevice.ui
- VMBootFromDeviceWindow() doesn't start the VM itself. It now "returns" the cdrom_location so caller can handle it in a better way:
- Improved dialog size and margins
- The dialog appears now very fast.
- If the user decides to cancel it, the VM is not created. It returns to the previous dialog so he can modify something and continue, or cancel the whole process creation.
Apart from this I added a properly **parent** argument to all dialogs (except current 'Template Manager', is it going to be removed?). This is very welcome when working with big screens. Now all dialogs are created centered on the current Qube Manager window.
=> VMBootFromDeviceWindow improvement and other minor fixes

qubesmanager/qube_manager.py
The function should always return Qt::ItemFlags type, even if the index
is invalid (like in a case where qube was just removed).
Fixes QubesOS/qubes-issues#6697
=> Fix return value of QubesTableModel.flags()

qubesmanager/settings.py
The property is a single string with space separated values, not a list
Fixes QubesOS/qubes-issues#6781
=> Fix DNS formatting

qubesmanager/global_settings.py
If user's trying to set as default NetVM a VM that has a 'default'
as netVM, the messege will elaborate a bit on what went wrong.
fixes QubesOS/qubes-issues#3567
=> Better error message on some cycles on setting default NetVM

debian/install, qubesmanager/global_settings.css, qubesmanager/global_settings.py, rpm_spec/qmgr.spec.in, setup.py, ui/globalsettingsdlg.ui
Transitional form: the functionality is the same, changes are
mostly visual, with only a minor addition of Version no,
release info link and version link.
fixes QubesOS/qubes-issues#6858
=> Improved design of Global Settings

qubesmanager/global_settings.py
Consider only non-zero exit code as a failure. Otherwise consider stderr
as just a warning.
QubesOS/qubes-issues#7306
=> Relax check on repository qrexec call

qubesmanager/tests/test_qube_manager.py
Since 267340f, update() is called after connecting to events stream,
which means there is always one expected call. Count extra calls above
that in the test.
QubesOS/qubes-issues#7362
=> tests: adjust expected update() call counts

qubesmanager/utils.py
After setting a vm.kernel to None, the property
vm.kernel outputted an empty string, not None object, which caused some funny problems with display of this property for Qube Settings (namely, we got a ' (current)' instead of a '(none) (current)'). This fixes this problem
and renames (none) to (provided by qube), because
that's what kernel = None should do.
fixes QubesOS/qubes-issues#7066
=> Fix display of kernels for Qube Settings

qubesmanager/backup.py, ui/backupdlg.ui
This adds a separate "save passphrase in backup profile" checkbox, which is unchecked by default and gets saved in the profile (implicitly, with the presence of the password field). As a result, users may save their settings without having to compromise on the security of their passphrase.
The big fat warning about the passphrase getting saved like that is now grayed out when not applicable.
Fixes QubesOS/qubes-issues#4819
=> Allow saving backup settings without passphrase

qubesmanager/log_dialog.py, qubesmanager/qube_manager.py
Previously the sorting order depended on alphabetically sorting the dictionary containing state, which was less than ideal. Now it will use a reasonable order (from more to less running, and within a given state, no updates come before updates-available).
Also fixes sorting the Backup column to actually use the include_in_backups state and the Label column to sort by label and type.
Also fixes the log browser to be selection-aware.
fixes QubesOS/qubes-issues#7073
fixes https://github.com/QubesOS/qubes-issues/issues/7633
fixes https://github.com/QubesOS/qubes-issues/issues/7776
fixes https://github.com/QubesOS/qubes-issues/issues/7715
=> Fix VM sorting order in Qube Manager if Sorting by State and fix log browser

qubesmanager/qube_manager.py
Some boolean variables were stored in QSettings, but not read correctly; QSettings stores True/False as 'true'/'false' strings.
fixes QubesOS/qubes-issues#7338
=> Correctly interact with QSettings

qubes-tools.menu
They are superceded by new developments in desktop-linux-manager.
=> Remove menu positions from old menu

qubesmanager/backup.py, ui/backupdlg.ui
Add a message to warn the user that a backup always includes metadata for all VMs on the system, to prevent e.g. leaking any sensitive qube names, should the filtered down backup get shared with somebody.
The message is not shown when all VMs are selected, to make it more noticeable when it could actually be relevant.
See also QubesOS/qubes-issues#2645
Further work: include similar precautions for the `qvm-create` CLI.
=> Warn about metadata leaks in backups

.pylintrc, qubesmanager/clone_vm.py, qubesmanager/firewall.py, qubesmanager/global_settings.py, qubesmanager/qube_manager.py, qubesmanager/qvm_template_gui.py, qubesmanager/settings.py
Instead of checking for isVisible, which can fail if we are on a different tab, check for isEnabled (also added appropriate disable commands where widget should be disabled).
fixes QubesOS/qubes-issues#7990
=> Fix detecting if widget was changed in VM settings

qubesmanager/multiselectwidget.py, qubesmanager/settings.py, ui/multiselectwidget.ui
Replace Available/Selected with a more explicit
"Available in qube/template" and "Shown in App Menu"
fixes https://github.com/QubesOS/qubes-issues/issues/8012
based on https://github.com/QubesOS/qubes-manager/pull/335 to avoid cherrypicking the pylint fixes back and forth.
=> Make available/selected apps in settings clearer

qubesmanager/qube_manager.py
run_service() can raise FileNotFoundError, so catch OSError and all of its subclasses.  Also catch the more general subprocess.SubprocessError instead of just subprocess.CalledProcessError.
Fixes: QubesOS/qubes-issues#8151
=> Catch more exceptions

qubesmanager/qube_manager.py
Simple modification.
~~Current limitations: If there's no QWT installed, this will silently fail ( the same as previously ). However, qvm-start will leave a humble line in the journal.~~
~~I thought of using os.path.exist() to detect if there's qwt image, but I'm not sure how to correctly implement it.~~
Current limitations: Path is hardcoded, and I think it will work awkwardly in sys-gui.
=> Preliminary GUI initiated QWT install

qubesmanager/qube_manager.py, qubesmanager/settings.py
Changing netvm checks if new netvm is running, and if not asks to start it - this didn't happen for default netvm. Now it will.
fixes QubesOS/qubes-issues#8156
=> Check if default_netvm is running when changing netvm

qubesmanager/qube_manager.py, qubesmanager/tests/test_qube_manager.py
Tests found an issue with switching netvm to the default one. Fix this.
Other test failures were caused by outdated tests - adjust accordingly.
=> Few tests adjustments and one bug fix

qubesmanager/settings.py
Need to properly indicate the new cloned qube name
fixes QubesOS/qubes-issues#8056
=> Fix error message when qube renaming fails.

qubesmanager/qube_manager.py
Don't have the manager wait for global config to be exited.
fixes QubesOS/qubes-issues#8387
=> Use subprocess.Popen to spawn global config in manager

qubesmanager/qube_manager.py
Some existing uses of Popen are not correctly using the parameters, and are causing zombie processes to be created.
Fix that with this simple trick.  Bugs hate it!
@marmarta
=> Fix uses of subprocess.Popen

qubesmanager/qube_manager.py
When updating qubes from Qube Manager, use the new GUI CLI.
requires https://github.com/QubesOS/qubes-desktop-linux-manager/pull/170
fixes QubesOS/qubes-issues#8117
fixes QubesOS/qubes-issues#6635
=> Use updater GUI for Qube Manager updates

qubesmanager/appmenu_select.py
Make it so that vm settings set menu-items feature instead of running qvm-appmenus
references QubesOS/qubes-issues#8494
=> Set menu-items feature instead of running qvm-appmenus

qubesmanager/global_settings.py
dom0 update dropdown will be disabled, but the
window will be shown.
fixes QubesOS/qubes-issues#8469
=> Show Global Settings even if no dom0 updates are enabled

qubesmanager/qube_manager.py, qubesmanager/settings.py
- Remove relative imports from qubesmanager
This is a mostly-cosmetic change, but enables running manager in-vm using mocks.
- Fix broken VM settings for a VM with temporary unlocked FW
=> Fix minor bug and improve qube manager imports

qubesmanager/appmenu_select.py, qubesmanager/settings.py
Follow-up to issue https://github.com/QubesOS/qubes-issues/issues/8836
To give users more choices to move applications between available and selected app lists
=> Enabling drag and drop between application lists

qubesmanager/clone_vm.py
QMessageBox.warning shows a scary exclamation mark, which is confusing when reporting success. Use QMessageBox.information instead.
Reported-by: Rafał Wojdyła <omeg@invisiblethingslab.com>
=> clone_vm: Don't use warning MessageBox on success

qubesmanager/tests/test_clone_vm.py
The clone operation uses QMessageBox.information now to inform about
success. Do not hang waiting for click there.
Fixes: 8500b36 "clone_vm: Don't use warning MessageBox on success"
=> tests: mock QMessageBox.information too

qubesmanager/utils.py
fixes: https://github.com/QubesOS/qubes-issues/issues/8694
Removing space and upper-case letters from qubes-manager configuration directory.
Migrating old config to new unified config directory.
=> Unify qubes-os XDG config directory

qubesmanager/create_new_vm.py
Select (None) for `Template` and `Networking` if user selects `TemplateVM` for `Type` in Create new qube dialog.
related: https://github.com/QubesOS/qubes-issues/issues/9174
=> Make `Create new qube` ComboBoxes smart

qubesmanager/qube_manager.py
resolves: https://github.com/QubesOS/qubes-issues/issues/7619
=> Refresh disk usage stats every 60s if focused

qubesmanager/device_list.py, qubesmanager/settings.py
implements QubesOS/qubes-issues/issues/9325
=> device identity

qubesmanager/device_list.py, qubesmanager/settings.py, test-packages/qubesadmin/device_protocol.py, test-packages/qubesadmin/devices.py
=> Fixup for q-dev

qubesmanager/qvm_template_gui.py
When opening template repo settings, open at those template repo settings, and not at the "General" page.
fixes QubesOS/qubes-issues#9530
requires https://github.com/QubesOS/qubes-desktop-linux-manager/pull/227
=> Open global config from template gui at correct location

qubesmanager/common_threads.py, qubesmanager/template_manager.py
Correct threaded behavior.
fixes QubesOS/qubes-issues#9738
=> Fix updating template switcher progress bar

qubesmanager/informationnotes.py, qubesmanager/qvm_about.sh, ui/informationnotes.ui
Add support for dnf5 (while preserving dnf4 compatibility)
Use Monospace font for Version information dialog
fixes: https://github.com/QubesOS/qubes-issues/issues/9798
=> Improve `Version information` dialog

icons/ban.svg, qubesmanager/qube_manager.py, qubesmanager/tests/conftest.py, qubesmanager/tests/test_qube_manager.py, resources.qrc
Qube Manager part of preventing qubes with `prohibit-start` from being started. Showing special status icon and disabling start and related buttons.
Supplements: https://github.com/QubesOS/qubes-issues/issues/9622
=> Add the feature to prohibit starting a qube

.gitignore, .gitlab-ci.yml, ci/requirements.txt, debian/control, debian/install, qubesmanager/appmenu_select.py, qubesmanager/tests/test_utils.py, qubesmanager/tests/test_vm_settings.py, qubesmanager/utils.py, rpm_spec/qmgr.spec.in
This PR contains 3 individual commits:
1. Fix for Drag-and-Drop in Qubes VM Settings GUI -> Applications tab
2. PyQt bindings for QImage tinting
3. Icons for Qubes VM Settings GUI -> Applications tab
fixes: https://github.com/QubesOS/qubes-issues/issues/9829
=> Settings applications tab

qubesmanager/qube_manager.py
Currently only unsets the backup check. Could not set it back.
=> Fix Backup toggle in Qube Manager

qubesmanager/settings.py, qubesmanager/tests/test_vm_settings.py, qubesmanager/utils.py, ui/settingsdlg.ui
Adds the user interface elements described at https://github.com/QubesOS/qubes-issues/issues/9750#issuecomment-2655149125 to the settings UI.
Not fully tested, thus not ready for merge. It seems to work for the most part, but my PR for the backend has a problem that keeps me from changing AppVM's templates for some reason.
=> Add boot mode support

qubesmanager/restore.py
Show scary exclamation mark in QMessageBox.warning. Use QMessageBox information instead. Resolves [qubes-issues/8538 ](https://github.com/QubesOS/qubes-issues/issues/8538) after https://github.com/QubesOS/qubes-manager/commit/8500b3654523ebd31a66a5880271585c9cba9dc5
=> restore_vm: Don't use warning MessageBox on success

qubesmanager/settings.py, qubesmanager/tests/test_vm_settings.py
Related issue: https://github.com/QubesOS/qubes-issues/issues/8551
Anon AppVM like anon-whonix needs an anon-gateway like sys-whonix to provide a correct level of anonymity and privacy. This commit adds a warning when a user try to connect a VM with the tag anon-vm to a Net Qube that does not have the tag anon-gateway
For tests to pass, https://github.com/QubesOS/qubes-core-admin-client/pull/343 must be merged.
=> add a warning box when connecting an anon vm to a non-anon gateway

qubesmanager/appmenu_select.py
Set a blank icon for missing apps. Scale up small icons
=> Improve and fix Settings App icons

qubesmanager/backup.py, qubesmanager/tests/test_backup.py, ui/backupdlg.ui
Provide user a selection of default compression filters in addition to the available recognised filters. Allow user to save the filter.
Requires: https://github.com/QubesOS/qubes-core-admin-client/pull/346
Related: https://github.com/QubesOS/qubes-issues/issues/8211
Related: https://github.com/QubesOS/qubes-issues/issues/8291
=> Allow user to select compression filter

qubesmanager/settings.py
- Hide `Host Bridge` and `PCI Bridge` devices since connecting them to a
qube would prevent it from booting
- If `port_id` is a path, replace the `-` delimiter with ` -> ` to make
it prettier and more meaningful
Related: https://github.com/QubesOS/qubes-issues/issues/8681
=> Make `Devices` tab prettier & safer
